//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongScreenerMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rhythm
    {
        public Rhythm()
        {
            this.Song = new HashSet<Song>();
        }
    
        public string RhythmID { get; set; }
        public string RhythmName { get; set; }
    
        public virtual ICollection<Song> Song { get; set; }
    }
}
