//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongScreenerMvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SongScreenerDBEntities : DbContext
    {
        public SongScreenerDBEntities()
            : base("name=SongScreenerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Artist> Artist { get; set; }
        public DbSet<Genre> Genre { get; set; }
        public DbSet<Intonation> Intonation { get; set; }
        public DbSet<Language> Language { get; set; }
        public DbSet<Rhythm> Rhythm { get; set; }
        public DbSet<Song> Song { get; set; }
        public DbSet<Tone> Tone { get; set; }
    }
}
