//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongScreenerMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        public string SongID { get; set; }
        public string SongName { get; set; }
        public string SongArtistID { get; set; }
        public string SongLanguageID { get; set; }
        public string SongGenreID { get; set; }
        public string SongIntonationID { get; set; }
        public string SongToneID { get; set; }
        public string SongRhythmID { get; set; }
        public string SongPath { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual Intonation Intonation { get; set; }
        public virtual Language Language { get; set; }
        public virtual Rhythm Rhythm { get; set; }
        public virtual Tone Tone { get; set; }
    }
}
