//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongScreenerMvc.Models.Entity
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class Artist_Mapping : EntityTypeConfiguration<Artist>
    {
        public Artist_Mapping()
        {                        
              this.HasKey(t => t.ArtistID);        
              this.ToTable("Artist");
              this.Property(t => t.ArtistID).HasColumnName("ArtistID");
              this.Property(t => t.ArtistName).HasColumnName("ArtistName").IsRequired().HasMaxLength(255);
              this.Property(t => t.ArtistGender).HasColumnName("ArtistGender");
              this.Property(t => t.ArtistHometown).HasColumnName("ArtistHometown");
              this.HasRequired(t => t.Gender).WithMany(t => t.Artist).HasForeignKey(d => d.ArtistGender);
              this.HasRequired(t => t.Hometown).WithMany(t => t.Artist).HasForeignKey(d => d.ArtistHometown);
         }
    }
}
