//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongScreenerMvc.Models.Entity
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class Hometown_Mapping : EntityTypeConfiguration<Hometown>
    {
        public Hometown_Mapping()
        {                        
              this.HasKey(t => t.HometownID);        
              this.ToTable("Hometown");
              this.Property(t => t.HometownID).HasColumnName("HometownID");
              this.Property(t => t.HometownName).HasColumnName("HometownName").IsRequired().HasMaxLength(255);
         }
    }
}
