//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongScreenerMvc.Models.Entity
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class Language_Mapping : EntityTypeConfiguration<Language>
    {
        public Language_Mapping()
        {                        
              this.HasKey(t => t.LanguageID);        
              this.ToTable("Language");
              this.Property(t => t.LanguageID).HasColumnName("LanguageID");
              this.Property(t => t.LanguageName).HasColumnName("LanguageName").IsRequired().HasMaxLength(255);
         }
    }
}
