//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable 1573
namespace SongScreenerMvc.Models.Entity
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SongScreenerDBEntities : DbContext
    {
        static SongScreenerDBEntities()
    	{ 
    		Database.SetInitializer<SongScreenerDBEntities>(null);
    	}
    	
    	public SongScreenerDBEntities() : base("name=SongScreenerDBEntities")
        {
        }
    	
    	public SongScreenerDBEntities(string nameOrConnectionString) : base(nameOrConnectionString)
    	{	
    	}
    
    	public SongScreenerDBEntities(string nameOrConnectionString, DbCompiledModel model) : base(nameOrConnectionString, model)
    	{
    	}
    
    	public SongScreenerDBEntities(DbConnection existingConnection, bool contextOwnsConnection) : base(existingConnection, contextOwnsConnection)
    	{
    	}
    
    	public SongScreenerDBEntities(DbConnection existingConnection, DbCompiledModel model, bool contextOwnsConnection) : base(existingConnection, model, contextOwnsConnection)
    	{
    	}
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {		
    		modelBuilder.Configurations.Add(new Artist_Mapping());
    		modelBuilder.Configurations.Add(new Extension_Mapping());
    		modelBuilder.Configurations.Add(new Gender_Mapping());
    		modelBuilder.Configurations.Add(new Genre_Mapping());
    		modelBuilder.Configurations.Add(new Hometown_Mapping());
    		modelBuilder.Configurations.Add(new Language_Mapping());
    		modelBuilder.Configurations.Add(new Song_Mapping());
        }
    	
        public DbSet<Artist> Artist { get; set; }
        public DbSet<Extension> Extension { get; set; }
        public DbSet<Gender> Gender { get; set; }
        public DbSet<Genre> Genre { get; set; }
        public DbSet<Hometown> Hometown { get; set; }
        public DbSet<Language> Language { get; set; }
        public DbSet<Song> Song { get; set; }
    }
}
