//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SongScreenerMvc.Models.Entity
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        public System.Guid SongID { get; set; }
        public string SongName { get; set; }
        public System.Guid SongArtistID { get; set; }
        public System.Guid SongLanguageID { get; set; }
        public System.Guid SongGenreID { get; set; }
        public int SongIntonation { get; set; }
        public int SongTone { get; set; }
        public int SongRhythm { get; set; }
        public string SongPath { get; set; }
        public System.Guid SongExtensionID { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Extension Extension { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual Language Language { get; set; }
    }
}
